--Simple Method:
SELECT THEMEPARK.PARK_CODE, PARK_NAME, TICKET_NO,
TICKET_TYPE, TICKET_PRICE
FROM THEMEPARK, TICKET
WHERE THEMEPARK.PARK_CODE = TICKET.PARK_CODE

-- With Natural Key word
SELECT PARK_CODE, PARK_NAME, TICKET_NO,
TICKET_TYPE, TICKET_PRICE
FROM THEMEPARK natural join TICKET
 

-- Join with Using Key word
SELECT PARK_CODE, PARK_NAME, TICKET_NO,
TICKET_TYPE, TICKET_PRICE
FROM THEMEPARK join TICKET using(park_code)


--inner join on clause
SELECT THEMEPARK.PARK_CODE, PARK_NAME, TICKET_NO,
TICKET_TYPE, TICKET_PRICE
FROM TICKET inner join THEMEPARK on THEMEPARK.PARK_CODE=  TICKET.PARK_CODE


-- alias
SELECT P.PARK_CODE, PARK_NAME, TICKET_NO,
TICKET_TYPE, TICKET_PRICE
FROM THEMEPARK  P inner join TICKET T on P.PARK_CODE=  T.PARK_CODE



--left join on clause

SELECT THEMEPARK.PARK_CODE, PARK_NAME, TICKET_NO,
TICKET_TYPE, TICKET_PRICE
FROM THEMEPARK LEFT join TICKET on THEMEPARK.PARK_CODE=  TICKET.PARK_CODE

--right join on clause
SELECT THEMEPARK.PARK_CODE, PARK_NAME, TICKET_NO,
TICKET_TYPE, TICKET_PRICE
FROM THEMEPARK right join TICKET on THEMEPARK.PARK_CODE=  TICKET.PARK_CODE




