--Creating Views !!!
CREATE VIEW EMP_WORKED AS
SELECT E.EMP_LNAME, E.EMP_FNAME, H.ATTRACT_NO,H.DATE_WORKED
FROM employee E JOIN hours H
ON E.EMP_NUM = H.EMP_NUM;

--Calling view
SELECT * FROM EMP_WORKED;

--Structure of table
DESCRIBE EMP_WORKED;

--Creating View
CREATE VIEW EMPFR AS
SELECT *
FROM EMPLOYEE
WHERE PARK_CODE = 'FR1001'
WITH CHECK OPTION;
 --We can't update this view because we implement the check option
 --We update but it will not
UPDATE EMPFR
SET PARK_CODE = 'UK3452' WHERE EMP_NUM = 100;

SELECT DISTINCT(SALE_DATE )
FROM SALES;
SELECT DISTINCT(DATE_FORMAT(SALE_DATE, '%D %b %Y')) FROM SALES;

SELECT DAYOFMONTH(EMP_DOB) AS 'Day', MONTH(EMP_DOB) AS 'Month',
YEAR(EMP_DOB) AS 'Year'FROM EMPLOYEE;

--EXERCISES
--1):
--FIRST CREATED VIEW THAT I ALREADY CREATED
CREATE VIEW EMPFR AS SELECT * FROM EMPLOYEE
WHERE PARK_CODE='FR1001' WITH CHECK OPTION;
--UPDATE
UPDATE EMPFR SET EMP_PHONE='324-9652' WHERE EMP_NUM=100;
--DISPLAY
SELECT * FROM EMPFR;
--DROP THE VIEW
DROP VIEW EMPFR;

--2):
CREATE VIEW EMP_WORKED AS SELECT EMP_NUM,PARK_CODE,PARK_NAME,EMP_LNAME,EMP_FNAME,EMP_HIRE_DATE,EMP_DOB
FROM EMPLOYEE NATURAL JOIN THEMEPARK;
--DISPLAY
SELECT * FROM EMP_WORKED;

--3):
SELECT EMP_FNAME,EMP_LNAME,PARK_NAME FROM EMP_WORKED;

--4):
SELECT PARK_NAME,MIN(LINE_PRICE),MAX(LINE_PRICE),AVG(LINE_PRICE) FROM THEMEPARK NATURAL JOIN SALES NATURAL JOIN SALES_LINE 
GROUP BY PARK_NAME;

--5):
SELECT DISTINCT(DATE_FORMAT(SALE_DATE,'%a %d %m %Y')) FROM SALES;

--6):
select emp_fname,emp_lname,emp_dob,concat(date_format(emp_dob,'%m'),'01',UPPER(SUBSTR(EMP_LNAME, 1, 6)))
as user_id from employee;

--7):
select emp_lname, emp_fname, emp_dob, date_format(emp_dob, '%D') as day from employee
where day(emp_dob) = '14';

--8):
select emp_fname,emp_phone,concat(substr(emp_phone,1,3), substr(emp_fname,1,2)) 
as user_id from employee;




