SELECT * FROM THEMEPARK;
SELECT AVG(TICKET_PRICE) FROM TICKET;

--TASK1
SELECT TICKET_NO, TICKET_TYPE, TICKET_PRICE FROM TICKET WHERE TICKET_PRICE >= (SELECT AVG(TICKET_PRICE) FROM TICKET);

--TASK2
SELECT PARK_CODE, SUM(LINE_QTY) FROM SALES_LINE NATURAL JOIN TICKET GROUP BY PARK_CODE HAVING SUM(LINE_QTY) >
(SELECT AVG(LINE_QTY) FROM SALES_LINE);

--TASK3
SELECT TICKET_NO, PARK_CODE, TICKET_PRICE
FROM TICKET
WHERE TICKET_PRICE > ALL (SELECT TICKET_PRICE FROM TICKET
WHERE TICKET_TYPE = 'CHILD');

--TASK4
SELECT TICKET_NO, TICKET_PRICE,
(SELECT AVG(TICKET_PRICE) FROM TICKET) AS AVGPRICE,
TICKET_PRICE - (SELECT AVG(TICKET_PRICE) FROM TICKET) AS DIFF
FROM TICKET;

--TASK5
SELECT TRANSACTION_NO, LINE_NO, LINE_QTY, LINE_PRICE
FROM SALES_LINE SL
WHERE SL.LINE_QTY > (SELECT AVG(LINE_QTY)
FROM SALES_LINE SA
WHERE SA. TRANSACTION_NO = SL. TRANSACTION_NO);

--LAB EXERCISES
--EXERCISE NO 1:
SELECT DISTINCT EMP_FNAME, EMP_LNAME FROM EMPLOYEE NATURAL JOIN HOURS WHERE HOUR_RATE > (SELECT AVG(HOUR_RATE) FROM HOURS);

--EXERCISE NO 2:
SELECT EMP_FNAME,EMP_LNAME,DATE_WORKED,(SELECT AVG(HOURS_PER_ATTRACT) FROM HOURS) AS AVERAGE, HOURS_PER_ATTRACT - 
(SELECT AVG(HOURS_PER_ATTRACT) FROM HOURS) AS DIFFERENCE FROM EMPLOYEE NATURAL JOIN HOURS;

--EXERCISE NO 3:
SELECT ATTRACT_CAPACITY FROM ATTRACTION WHERE ATTRACT_CAPACITY <= (SELECT AVG(ATTRACT_CAPACITY) FROM ATTRACTION);